baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'SVS'

[module]
[[module.imports]]
path = 'github.com/alex-shpak/hugo-book'

[markup.goldmark.renderer]
  unsafe = true

[params]
BookTheme = 'dark'
BookSection = '/'

