baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'SVS'

[module]
[[module.imports]]
path = 'github.com/McShelby/hugo-theme-relearn'

[markup.goldmark.renderer]
unsafe = true

[params]
collapsibleMenu = true
[[params.themeVariant]]
auto = ['script-blocks-light', 'script-blocks-dark']
identifier = 'script-blocks-auto'
name = 'Script Blocks Light/Dark'